curl -X POST http://localhost:8080/command/register_new_event \
     -H "Content-Type: application/json" \
     -d '{
           "titre_de_levenement": "Conférence Rust 2024",
           "type_de_levenement": "rencontre",
           "date": "2024-12-09T14:30:00Z",
           "lieu": "Paris, France",
           "organisateur": "Rust France",
           "description": "Une conférence dédiée au langage Rust."
         }'

curl -X GET 127.0.0.1:8080/ready 

